### ISSUE TITLE
Cannot find openfabmap source in opencv

### ISSUE THREAD

**Issue by huang-qiao** [arrenglover/openfabmap#13]
Hi,

I found there's an openfabmap implementation in opencv 2.4
[http://docs.opencv.org/2.4/modules/contrib/doc/openfabmap.html](http://docs.opencv.org/2.4/modules/contrib/doc/openfabmap.html) 
but I cannot find the source code in official OpenCV repo (Itseez/opencv, opencv_contrib, opencv_attic)

Did I missed anything?

Thanks!

**Comment by arrenglover** [comment]
OpenFABMAP hasn't been ported to OpenCV 3.0 in which all contributed modules need to be in the opencv_contrib repo. OpenFABMAP should be in the source for all OpenCV2.4.x
