### ISSUE TITLE
Was an inverted index added to speed up in the openfabmap v2.02?

### ISSUE THREAD

**Issue by ErnstHowie** [arrenglover/openfabmap#15]
Thanks for such a great implementation of FabMap! 
Was an inverted index added to speed up in the OpenFabMap v2.02?

**Comment by ErnstHowie** [comment]
@arrenglover  @kmactavish

**Comment by arrenglover** [comment]
Yep, the inverted index was implemented.

**Comment by ErnstHowie** [comment]
Thanks, @arrenglover .  Here I have another question:
My experimental results with the implementation of OpenFabMap v2.02 show that the computational complexity of FAM-MAP 2.0 is linear with the number of the database images (i.e., previously visited places).
Did I make it right?

**Comment by arrenglover** [comment]
Yes, the computational complexity is linear in the number of locations. The FAB-MAP 2.0 inverted index drastically reduced the computation required, making it much faster. Figure 9 in "Highly Scalable Appearance-Only SLAM – FAB-MAP 2.0" shows the same linear complexity.

**Comment by ErnstHowie** [comment]
Thanks a lot.
