### ISSUE TITLE
Load vocabularytraindata.yml problem in openfabmap

### ISSUE THREAD

**Issue by CharleneZhao** [arrenglover/openfabmap#17]
I am sorry that bother you. I think it's a little problem but I can't figure it out :( 
I follow the function steps sequentially. In the second function I load the train.avi and generate vocabularytraindata.yml. In the third function, it needs to load this yaml file, but I got an error with opencv:
OpenCV Error: Parsing error (vocabularytraindata.yml(132841098): Missing, between the elements) in icvYMLParseValue
I am sure that  vocabularytraindata.yml has been generated and I have set the file path in the settings.yml. Anyone has the same problem?

**Comment by arrenglover** [comment]
Hi,
Are you still having this problem?
What version of OpenCV are you using? It is most likely related to a new version (3.0?) or a mismatch between versions if you have more than one installed.
I will try to do the training steps and see if I get the same error. Updating OpenFABMAP to opencv3.0 is on my to-do list when I get time.
Arren.

**Comment by CharleneZhao** [comment]
Thanks for your attention very much!
I have solved this problem now. At first, I  just set the file path as "vocabularytraindata.yml", and the vocabularytraindata.yml can be generated in the bin folder, but cannot be loaded. I found that if I set the complete file path in the settings.yml, the yaml file will be loaded.
