### ISSUE TITLE
Ask Help for Visual Place Recognation "Gardens Points"

### ISSUE THREAD

**Issue by zjcs** [arrenglover/openfabmap#22]
Hi, Dear Aren Glover

As a researcher in visual place recognation, I am trying to test the performances of different algorithms. Unfortunately, the url of "Gardens Points" seems not to be unavaiable because of the automatical jump to QUT. 

Do you have any ideas to download this dataset?

Thank you very much.

P.s. The previouse URL is : https://wiki.qut.edu.au/display/cyphy/Day+and+Night+with+Lateral+Pose+Change+Datasets

**Comment by arrenglover** [comment]
The direct link to the Garden's Point data-set is here:

https://mega.nz/#!XAZHgZYa!Rp83z96sc5iiSeV2LC1INyNTYt3JM2utQ8_9yms3Fg8

let me know if that doesn't work

All the best

**Comment by zjcs** [comment]
Sorry to Reply late. 

I have downloaded the dataset successfully following your new link.

Thank you very much!
