### ISSUE TITLE
About visualisation?

### ISSUE THREAD

**Issue by xlong0513** [arrenglover/openfabmap#23]
Hi, everyone. I wonder how to get the visualisation results? I have followed the [Wiki](https://github.com/arrenglover/openfabmap/wiki/Usage) "Visualising Results", and I have got the "results.txt". However, when i import the data into Matlab, it says the data is too big, and the computer died. Did i miss some key step?

Besides, how can i visualize the recognition results real time?

**Comment by arrenglover** [comment]
It seems like your data file is too large (too many images) to load into matlab given the memory available of your computer. You could test this by using a smaller dataset and verifying it can be loaded into matlab. (the results.txt is just a csv file, so there is nothing fancy here).

There is no visualisation about the inference during the operation. If you understand what is happening in https://github.com/arrenglover/openfabmap/blob/master/samples/openFABMAPcli.cpp you should be able write how you wish to visualse step-by-step as fabmap is called.

**Comment by xlong0513** [comment]
Hi, @arrenglover thanks for the quick reply. I see. But I got  another question here. Now that I got the confusion matrix, how can i get the  PR curve from the confusion matrix, for example
![image](https://user-images.githubusercontent.com/35829321/78865964-25a9ce80-7a71-11ea-87c5-d9f48136eeb4.png)

**Comment by arrenglover** [comment]
There is no code in openfabmap that will calculate the PR curve for you, sorry. I also don't have anything that I can easily share with you. There should be plenty of resources available after a quick search though.

**Comment by xlong0513** [comment]
Hi, @arrenglover, Sorry to bother again. As you give the dataset [St. Lucia Multiple Times of Day and Other Datasets](https://github.com/arrenglover/openfabmap/wiki/Datasets) in README, and it mentions your another paper "FAB-MAP + RatSLAM: Appearance-based SLAM for Multiple Times of Day ", So I wonder where I can find the source of this paper? Or is it not open source?

**Comment by arrenglover** [comment]
@xlong0513 the experiments were run by first running this openfabmap code to generate the loop-closure likelihoods, and running RatSLAM using the loop-closure likelihoods to generate the maps, and stitch locations together. 

The **exact code used in those experiments, I don't believe is available**, but I believe the ratslam code here: https://github.com/davidmball/ratslam is still current, and you could replicate similar experiments with it.

All the best.

**Comment by xlong0513** [comment]
@arrenglover Oh, I see. Thanks a lot.
