### ISSUE TITLE
Can not find the parameters under the FABMAP VISUALISATION heading in the settings file

### ISSUE THREAD

**Issue by LuoXin0826** [arrenglover/openfabmap#26]
Hi everyone, I've followed the steps in visualization and got the result.txt file, but I could not see the image thumbnails. I was thinking that it may be the problem of monitor size and thumbnail size, so I get into the setting file, but I cannot find these two parameters. Could anyone tell me where I can find these parameters?

**Comment by arrenglover** [comment]
Hi @LuoXin0826 . There are two ways to visualise what is going on with openFABMAP.

1. Qualitative visualisation of the features you are detecting, mostly to estimate if you are extracting a "good" amount of features, and that they are consistent amounts over the dataset. It just shows the input to the fabmap algorithm.
1. Visualise the final results - using the results.txt file you can load it in your preferred way (e.g. Matlab) and use your own plotting tools to visualise the final results and do any extra analysis.

From your issue I'm not sure exactly what you were expecting - let me know if you need more details on either of these steps. Here's the instructions: https://github.com/arrenglover/openfabmap/wiki/Visualisation

**Comment by LuoXin0826** [comment]
Thank you for your response! I've loaded the result.txt file to matlab, but I'm not sure what's those numbers representing

**Comment by arrenglover** [comment]
For example check out the original FAB-MAP page: http://www.robots.ox.ac.uk/~mjc/Software.htm

This image: 
![image](https://user-images.githubusercontent.com/9265237/95836546-db671a00-0d3f-11eb-9c11-9aff1c6d4db4.png)

shows the probabilities of any one appearance matching a previously seen place. A typical "loop closure" could like like this - where the main diagonal is the locations matching to themselves with high probability and the secondary diagonal is the "second loop" matching to the original locations.

hope it helps
