### ISSUE TITLE
Cannot get the results.txt

### ISSUE THREAD

**Issue by jyknz** [arrenglover/openfabmap#27]
Hi guys,

I've manage the change settings.yaml to run my dataset, but it does not seem to generate results.txt.
Is there anything I have to do to get results.txt?

**Comment by arrenglover** [comment]
Hi @jyknz 

You should specify the results file in the settings.yml. See here: 
https://github.com/arrenglover/openfabmap/blob/47fef64e2cb6407604cbce415a44a9b9e6219da8/samples/settings.yml#L43

double check that at the location specified you have permission to create a file etc. (you might need to create the folders if you have specified some that don't exist). 

If that doesn't help please give more information about the process that you are doing to produce the results.
