### ISSUE TITLE
does it support for opencv 4.2?

### ISSUE THREAD

**Issue by GracefulMan** [arrenglover/openfabmap#28]
when i installed the package, i modified the setting file(the avi file path) and run the command "bin/openFABMAPcli -s ../samples/settings.yml", but i get the following error:

"Could not create Descriptor Extractor. Please specify extractor type in settings file"
Feature Extractor error.

but i have setted extractor type.
![Screenshot from 2021-07-07 10-12-53](https://user-images.githubusercontent.com/41041321/124689921-fa2fc100-df0b-11eb-9def-7c5cae539362.png)

**Comment by ncgoh** [comment]
Did you solve it? I have the similar issue with opencv 4.2. It state that "Could not create detector class. Specify detector mode in settings file" but I have selected the detector mode.
